CREATE TABLE client
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active         BOOLEAN,
    password       VARCHAR(100),
    identification VARCHAR(20),
    name           VARCHAR(100),
    gender         VARCHAR(10),
    birth_date     DATE,
    address        VARCHAR(255),
    phone          VARCHAR(20),
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP
);