CREATE TABLE account
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT,
    number     VARCHAR(20) UNIQUE NOT NULL,
    type       VARCHAR(20)        NOT NULL,
    balance    NUMERIC(19, 2)     NOT NULL,
    active     BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_account_number ON account (number);


CREATE TABLE transaction
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT         NOT NULL,
    value             NUMERIC(19, 2) NOT NULL,
    initial_balance   NUMERIC(19, 2) NOT NULL,
    available_balance NUMERIC(19, 2) NOT NULL,
    created_at        TIMESTAMP
);

CREATE INDEX idx_transaction_account_id ON transaction (account_id);